export const ActionTypes = {
    TASK_LOAD_START:"TASK_LOAD_START",
    TASK_LOAD_FAIL:"TASK_LOAD_FAIL",
    TASK_LOAD_SUCCESS:"TASK_LOAD_SUCCESS",
    ADD_TASK:"ADD_TASK",
    DELETE_TASK:"DELETE_TASK",
    UPDATE_TASK:"UPDATE_TASK",
    UPDATE_FOCUSING:"UPDATE_FOCUSING",
}